### ISSUE TITLE
Minor usability improvement: add clock icon or similar to sitetree pages that have a publish/unpublish date set

### ISSUE THREAD

**Issue by clarkepaul** [symbiote/silverstripe-advancedworkflow#101]
While viewing the sitetree it would be useful to see which pages have a publish/unpublish date set, this could be achieved by a clock icon at the right side of the label or above the page icon.

**Comment by robbieaverill** [comment]
I think this is a duplicate of https://github.com/symbiote/silverstripe-advancedworkflow/issues/75
