### ISSUE TITLE
Error when trying to progress entire workflow as admin only in the same session

### ISSUE THREAD

**Issue by surf9** [symbiote/silverstripe-advancedworkflow#142]
When I reach a "Simple Approval Workflow Action" on a fairly complex workflow when logged in as an admin I get the following error message:

"Error at line 300 of /var/www/aep-silverstripe/advancedworkflow/code/dataobjects/WorkflowInstance.php"

I get the above error message as a Silverstripe pop up message (black background in top right corner).

Currently, to resolve issue I need to refresh the page or navigate away from current screen then navigate back. I notice the first "Simple Approval Workflow Action" is fine. But when it reaches the subsequent "Simple Approval Workflow Action" the issue appears. It appears the issue is caused by posting from the previous action. As a result, the previous transitions that was posted is reused in the next action. When perform a refresh you are not posting and therefore pulls the correct transition instead of reusing the posted transitions. The current action title is also not updated after posting. Instead, the previous action title is kept. A page refresh resolve issue.

When viewing the code in line 300 the exception that gets initiated is:

```php
public function performTransition(WorkflowTransition $transition) {
    // first make sure that the transition is valid to execute!
    $action = $this->CurrentAction();
    $allTransitions = $action->BaseAction()->Transitions();
    $valid = $allTransitions->find('ID', $transition->ID);
    if (!$valid)
    { throw new Exception ("Invalid transition state for action #$action->ID"); }
```

**Comment by robbieaverill** [comment]
Closed as the discussion was taken off GitHub
