### ISSUE TITLE
"Save" button on actions continues to appear active when error occurs

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-advancedworkflow#145]
Creating an AssignUsersToWorkflowAction without a title displays an error that you’ve omitted it, but the “save” button continues indicating that it’s doing something. (Although you can still press it).

This is confusing from a user's persepctive as it doesn't appear as though the "save" button can be clicked.

Solution: If an error has occured, remove the "active" animation from the "Save" button.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
