### ISSUE TITLE
Add module to scrutinizer

### ISSUE THREAD

**Issue by chillu** [symbiote/silverstripe-advancedworkflow#147]
Could you please add the module to scrutinizer? https://scrutinizer-ci.com/g/new. We're keeping track of all modules we use on our contributions dashboard (github-dashing.herokuapp.com), and I've added scrutinizer quality and coverage scores there. Doesn't require any config, just four clicks. You'll have to click "Schedule inspection" for the first run, after that it should kick off automatically on commits.

If you feel like it, you could also add me as a collaborator :) There's a "Add collaborators to your repository" option on the homepage.

We're experimenting with a more fine tuned config, including code coverage running on travis, but that's not really to roll out yet (https://github.com/stojg/silverstripe-timeline). Happy to hear feedback and get help of course :)

**Comment by robbieaverill** [comment]
@nglasl do you think this is something that Symbiote could do?

**Comment by nglasl** [comment]
@robbieaverill, just curious on these..

a) I thought I remember reading something that mentioned you were using something else now?
b) I believe these had it already configured, but it was removed when the vendor changed. So perhaps it is something that you already have access to?
c) Is the plan to have this across every supported module?

**Comment by robbieaverill** [comment]
Hey @nglasl:

a) We're using Codecov.io for the code coverage, but still Scrutinizer for static analysis
b) Quite possibly. I can't set it up though as it needs to be done by an admin. It's pretty quick: https://scrutinizer-ci.com/g/new -> enter repo name -> select PHP -> OK -> done
c) Yeah - our standard CI toolchain will be Travis CI for builds, Scrutinizer CI for static analysis and Codecov.io (via Travis) for code coverage

**Comment by nglasl** [comment]
@robbieaverill, that makes sense. I've now added this (and the other modules with config present). You're welcome to add something into the README that points to the build, but please let me know if you're having any issues.

**Comment by dhensby** [comment]
With scrutinizer it doesn't map back to the new repo on renames, you'll have to update it on this page: https://scrutinizer-ci.com/g/silverstripe-australia/silverstripe-advancedworkflow/settings#change_form_name_control_group

**Comment by nglasl** [comment]
Sorry, but that page throws a 404 for me. The scrutinizer profile can be found over at the following https://scrutinizer-ci.com/g/symbiote/silverstripe-advancedworkflow/.

**Comment by robbieaverill** [comment]
Has been done for a while, closing
