### ISSUE TITLE
Incorrect spacing above GridField under "Active" & "Completed" subtabs

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-advancedworkflow#21]
Switching between the "Active" and "Completed" subtabs, an inconsistent space can be observed above each GridField. This seems to occur regardless of whether the GridField contains any rows or not.

Firefox 15 / Chrome 22 OS X 10.7.4

**Comment by robbieaverill** [comment]
Closing as this issue hasn't seen any attention since 2012, so if it's a core issue it's probably fixed now
