### ISSUE TITLE
Advance workflow module and translatable module

### ISSUE THREAD

**Issue by surf9** [symbiote/silverstripe-advancedworkflow#225]
Hi there.

I'm just wondering regarding the use of the advance workflow module with the translatable module. If I have an English page and create some translated content for it. When I start a workflow for the English page and eventually approve the workflow for publishing does the translated pages get published automatically or do I need to publish each translated page separately?

Please let me know.

Thanks.

**Comment by robbieaverill** [comment]
@surf9 I'm going to close this primarily because it's stale, but also because it seems like a question rather than a bug report. Feel free to reopen if you're still having problems!
