### ISSUE TITLE
Create a "docs" folder and move a new SS3 how-to, readme etc

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-advancedworkflow#26]
The suggested directory hierarchy for SS modules includes provision for a "docs" directory for project-specific documentation, ultimately viewable by docsviewer.

Suggest a "docs" folder is added to the project and at least initially a new SS3 How-to.md is added, with subsequent how-tos and tute's being added to this directory as more are written.

@nyeholt, refer to shared Google doc (upon completion to our satisfaction) for the content of a .md how-to as a starting point for SS3. The existing 2.4 docs could also be added and we then layout the docs directory thus:

docs/2.4
docs/3.0

**Comment by robbieaverill** [comment]
has been done
