### ISSUE TITLE
Workflow steps can't be limited to subsite-only groups

### ISSUE THREAD

**Issue by chillu** [symbiote/silverstripe-advancedworkflow#264]
It's quite common to give CMS authors and publishers access to a specific subsite only, by creating a new group in admin/security with permissions like "Access to Pages", but limited to one subsite.

You can apply a workflow to all pages on a subsite (by individually setting it on each root level page...). But there's no way to select a subsite-specific group in admin/workflow because they're prefiltered to only show groups with SubsiteID=0.

The effect is that any CMS user who needs to publish pages within a workflow context needs to be a member of a group which has permissions on _all_ subsites.

One way to solve this is allow access to admin/workflow on subsites (currently the menu entry is hidden), although that might cause more regressions than it fixes. The other way would be to remove the subsite filtering on the group dropdown.

**Comment by tractorcow** [comment]
This seems like it's an issue with Subsites, not with advanced workflow.

Unlike other modules, Subsites does NOT have a standard "generic" extension you can apply to a dataobject to make it subsite-specific.

**Comment by tractorcow** [comment]
I've raised this at https://github.com/silverstripe/silverstripe-subsites/issues/254

**Comment by robbieaverill** [comment]
Closing in favour of https://github.com/silverstripe/silverstripe-subsites/issues/254
