### ISSUE TITLE
3.8 - PublishOnDate backdoor

### ISSUE THREAD

**Issue by jakxnz** [symbiote/silverstripe-advancedworkflow#303]
The scheduled publishing date can be bypassed if the user assigns `PublishOnDate` (_"Scheduled publish date"_) before a `WorkflowDefinitionID` (_"Applied Workflow"_) is assigned and disables the `PublishOnDate` cms field. The pre-assigned `PublishOnDate` value is then overlooked during `PublishItemWorkflowAction::execute()`, where only `DesiredPublishDate` is checked for, and the item is published.

**PublishItemWorkflowAction::execute()**:

```
. . .
if ($target->DesiredPublishDate) {
	$target->PublishOnDate = $target->DesiredPublishDate;
	$target->DesiredPublishDate = '';
	$target->write();
} else {
	if ($target->hasMethod('doPublish')) {
		$target->doPublish();
	}
}
. . .
```

**Comment by SilbinaryWolf** [comment]
Fixed on PR https://github.com/symbiote/silverstripe-advancedworkflow/pull/304
