### ISSUE TITLE
Update module to PSR-2 and fix indenting

### ISSUE THREAD

**Issue by chrispenny** [symbiote/silverstripe-advancedworkflow#309]
I'm quite keen to create a pull request to update all the indenting to match `.editorconfig` and to update to PSR-2, but before I do, I just wanted to check if that would be something that you're all ok with me doing?

There are a fair few Pull requests that would be affected as a result.

**Comment by robbieaverill** [comment]
@chrispenny FYI PSR-2 is part of SS4, I've included it in a PR at #314

**Comment by dhensby** [comment]
fixed with #314
