### ISSUE TITLE
v3.8.2: QueuedJobs are deleted before they can mark themselves as completed.

### ISSUE THREAD

**Issue by chrispenny** [symbiote/silverstripe-advancedworkflow#321]
`WorkflowPublishTargetJob` is deleted by the Page (using `clearUnPublishJob()`) when it's `PublishOnDate` and/or `UnPublishOnDate` is removed as part of it's `onBeforeWrite()` method. This then causes an exception when the Job tries to mark itself as complete (as it has been deleted).

Fix:
https://github.com/symbiote/silverstripe-advancedworkflow/pull/311/files

**Comment by robbieaverill** [comment]
Fixed in #311
