### ISSUE TITLE
Custom Workflow Title not retained

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-advancedworkflow#326]
PHP 5.6.32 / v3.6.2 / v4.x-dev

A Custom Workflow Title is not retained when basing it off a templated example e.g .the built-in "Review and approve" workflow, but it does work if you create a new "empty" workflow (i.e you don't base it off any pre-existing workflow)

**Comment by robbieaverill** [comment]
Reproduced on CWP 1.7, thanks!

**Comment by robbieaverill** [comment]
Pull request at #329
