### ISSUE TITLE
Admin saving workflow definition to a page “Save draft” button change to “Save”

### ISSUE THREAD

**Issue by robbieaverill** [symbiote/silverstripe-advancedworkflow#335]
![fix3](https://user-images.githubusercontent.com/5170590/34658598-2056c956-f495-11e7-98a0-7100076129e7.jpg)

cc @clarkepaul

**Comment by robbieaverill** [comment]
@clarkepaul this actually seems correct, because you're saving a draft of a page and that button is triggering that action. Have I misunderstood something?

**Comment by clarkepaul** [comment]
Yeah this isn't really a Advanced Workflow issue but a general UI enhancement. The main actions in this area should read "Save | Publish" but that should be an issue already raised in CMS/Admin repo so this can be closed (I'll see if I can locate the appropriate issue).

**Comment by robbieaverill** [comment]
Cool
