### ISSUE TITLE
Admin can not approve/reject "Paused" approvals from model admin (Active) OR from pages (Workflow Log)

### ISSUE THREAD

**Issue by sachajudd** [symbiote/silverstripe-advancedworkflow#340]
Following on from @raissanorth's findings: "As an admin, I am able to go to the edit menu for an individual approval job. When I select 'approval' as the next job and hit the save button the following happens:

- The workflow status remains 'paused' rather than changing to 'completed'
- I get redirected to the content page, rather than the backlog page
- The content approved by me is not published."

Model Admin view:
![awf](https://user-images.githubusercontent.com/24258161/35079634-a4d64e74-fc6d-11e7-888e-28a23af605f5.png)

Once approved the workflow status should switch to "Completed" and move to the "Completed" tab.

Pages are also missing approve/reject toolbar for admin SS3 screenshot:
![image](https://user-images.githubusercontent.com/24258161/35080016-dc0bd556-fc6f-11e7-83ba-77e3c02ab34e.png)

**Comment by phptek** [comment]
Ditto with admin-user and a user with privileges enough to see these UI controls. See also #349 which may be related.

**Comment by NightJar** [comment]
Testing at `5.0.4` I cannot replicate these issues.
If anyone is able to (@phptek ) please feel free to reopen.
