### ISSUE TITLE
Unable to sort actions/transitions.

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-advancedworkflow#346]
mod-php7.1 / 5.0.x-dev / framework 4.0.2

I cannot sort the actions list as part of a workfow definition. The XHR request returns the message: `An invalid class to order was specified`.

Looking at the POST vars that `WorkflowField` is seeking, it requires a FQ namespace, not a single (old skool) class-name, but it's actually the latter that the XHR request is sending.

**Comment by phptek** [comment]
I imagine modding the client JS to pass a namespaced class to the controller would sort it:

```
class: 'Symbiote\\AdvancedWorkflow\\DataObjects\\WorkflowAction',
...
class: 'Symbiote\\AdvancedWorkflow\\DataObjects\\WorkflowTransition',
```

instead of:

```
class: 'WorkflowAction',
...
class: 'WorkflowTransition',
```

**Comment by phptek** [comment]
Once you fix that, it looks like a bad set of ids is being passed to the controller via `$(this).data('id')` but I have no idea how this JS stuff works these days *sigh*

**Comment by phptek** [comment]
Good idea. Although there's a president in other modules (asset-admin I think) thst does it in the JS. Besides, there's at least one other JS fix needed for the lack of an array of ids issue that I also noted. So may as well patch just the one file aye?

**Comment by robbieaverill** [comment]
Just checked, no injection definitions, your original idea is what we need to do. How do you feel about a pull request? =)

**Comment by phptek** [comment]
Not much point as things still break without the list of ids POSTed to the controller, which would still be broken. I'm finding the JavaScript even harder to reason about than entwine, and gave it an hour this morning but couldn't figure it out :-(
