### ISSUE TITLE
Broken Requirements in WorkflowEmbargoExpiryExtension

### ISSUE THREAD

**Issue by phptek** [symbiote/silverstripe-advancedworkflow#363]
On line 102 of `WorkflowEmbargoExpiryExtension.php`, This CSS file doesn't exist and is the last remnant of a time when we were using jQuery UI datepickers

```
        Requirements::css(
            $module . ':javascript/jquery-ui/timepicker/jquery-ui-timepicker-addon.css'
        );
```

**Comment by robbieaverill** [comment]
This was fixed recently in https://github.com/symbiote/silverstripe-advancedworkflow/pull/361

**Comment by phptek** [comment]
Sweet, thanks. I was using one of the 400 composer recipes. Have overriden that now with composer alias. Cheers.

**Comment by robbieaverill** [comment]
Cool - the next round of releases will be in a week or so probably
