### ISSUE TITLE
UX Template appears to be optional when required

### ISSUE THREAD

**Issue by raissanorth** [symbiote/silverstripe-advancedworkflow#368]
When defining a new workflow, the field title implies that a template is optional, however a warning is shown when none is chosen:

![image](https://user-images.githubusercontent.com/14869519/42064388-26450036-7b8a-11e8-94d0-6a84ec6ab8ed.png)

Using `symbiote/silverstripe-advancedworkflow 5.0.7`

**Comment by robbieaverill** [comment]
Fixed with #369
