### ISSUE TITLE
AdvancedWorkflowAdmin getEditForm() to allow post hook.

### ISSUE THREAD

**Issue by jules0x** [symbiote/silverstripe-advancedworkflow#379]
In order to be able to modify the gridfield in the admin, I needed to fork this module and add an extend hook. I added the below at the end of the getEditForm() function.

$this->extend('updateEditFormAfter', $form);

This allowed me to modify the admin to show a separate gridfield of pending workflow instances per subsite. 
E.g. 3 items for Main site, 4 items for Subsite1 and 2 items for Subsite2.

There is already an extend hook at the start of the file, but this would not work for my case. Is this something that would make sense to add?

à la https://github.com/jules0x/silverstripe-advancedworkflow/commit/38a7fc4ae90ad4d4a522ecf00401ac4182618cb5

**Comment by robbieaverill** [comment]
Done in #383, thanks @jules0x
