### ISSUE TITLE
Versioning / branching tidy up

### ISSUE THREAD

**Issue by sminnee** [symbiote/silverstripe-advancedworkflow#39]
Can I suggest the following to tidy up the branches?
- Drop the ss3 branch; it's been merged into master.
- Create a branch `1.4`  based on the current `ss24` branch, and delete the `ss24` branch.  That will be the final 2.4-compatible version.  1.5 will require SS3.

Alongside this I will submit `composer.json` pull requesets files to `master` (requiring SS `>=3.0.0`) and the existing `ss24` branch (requiring SS `>=2.4.0,<3.0.0`).

This will mean that SilverStripe 2.4 users can install 1.4.x-dev via composer, and SilverStripe 3.0 users can install dev-master.  In either case, specifying no specific version will install the correct one.

**Comment by robbieaverill** [comment]
The branching is tidy at the moment :)
