### ISSUE TITLE
Diff view for content doesn't work when new lines are added

### ISSUE THREAD

**Issue by robbieaverill** [symbiote/silverstripe-advancedworkflow#396]
**Workflow 5.1.x-dev, SS 4.3.x-dev and Chrome 73 on MacOS**

When viewing the changes for content where new HTML elements have been added, the diff generator wraps the new tags (eg `<p>` tags) in `<ins>` and `<del>` etc, but these are no longer displayed visually in the browser as changes.

You can work around this by setting `.workflow-field-diff ins p { background-color: inherit; }` or by setting `.workflow-field-diff ins { display: inline-block; }` (and the same for `del`, but I'm not sure which is the best way to fix this with CSS.

**Comment by robbieaverill** [comment]
Lowered effort rating - we can fix this with CSS

**Comment by robbieaverill** [comment]
PR at https://github.com/symbiote/silverstripe-advancedworkflow/pull/398

**Comment by ScopeyNZ** [comment]
Closed in #398
