### ISSUE TITLE
Change to mark fields readonly instead of form conflicts with SilverStripe FieldList

### ISSUE THREAD

**Issue by jules0x** [symbiote/silverstripe-advancedworkflow#400]
Since upgrading to 5.2, the change in the below commit has meant I can't access pages that have an active workflow.

https://github.com/symbiote/silverstripe-advancedworkflow/commit/45fcc27e6dbff328a7978e443b7554570233bc07

The error I receive is`Uncaught BadMethodCallException: Object->__call(): the method 'isReadonly' does not exist on 'SilverStripe\Forms\FieldList'`

I have forked to undo this change, but so far do not see how this would be resolved.

**Comment by robbieaverill** [comment]
Thanks. Which specific version are you using?

**Comment by jules0x** [comment]
5.2.0

I haven't completely eliminated our own codebase from causing this, but better to log early in case this has been seen by others.

**Comment by robbieaverill** [comment]
I think given that the highlighted change was for performance reasons, we can revert it and tag a new release

**Comment by robbieaverill** [comment]
Oh I see, that change required https://github.com/silverstripe/silverstripe-framework/pull/8853 which hasn't been merged

**Comment by robbieaverill** [comment]
I've adjusted the code to allow the new API if it exists or revert to the old behaviour: https://github.com/symbiote/silverstripe-advancedworkflow/pull/401

**Comment by robbieaverill** [comment]
Merged and tagged in 5.2.1
