### ISSUE TITLE
[Emergency] Uncaught Error: Call to a member function map() on boolean

### ISSUE THREAD

**Issue by jules0x** [symbiote/silverstripe-advancedworkflow#406]
symbiote/silverstripe-advancedworkflow/src/Extensions/WorkflowApplicable.php

Line 134 tries to map, but there may not be any workflow definitions.

```
129         if (Permission::check('APPLY_WORKFLOW')) {
130             $definition = new DropdownField(
131                 'WorkflowDefinitionID',
132                 _t('WorkflowApplicable.DEFINITION', 'Applied Workflow')
133             );

134             $definitions = $this->getWorkflowService()->getDefinitions()->map()->toArray();

135             $definition->setSource($definitions);
136             $definition->setEmptyString(_t('WorkflowApplicable.INHERIT', 'Inherit from parent'));
137             $tab->push($definition);
```

I've only experienced this issue on Subsites... and the workaround is to create a workflow definition.

**Comment by NightJar** [comment]
This seems mighty odd @jules0x - can you please confirm what version you're experiencing this with?

5.2 for example should never see `null` returned from `getDefinitions`:
https://github.com/symbiote/silverstripe-advancedworkflow/blob/5.2/src/Services/WorkflowService.php#L219

**Comment by maxime-rainville** [comment]
I'll close this for now. If this is still affecting some users, please comment below with some reproduction steps and we can have another look.
