### ISSUE TITLE
Plain text vs html emails

### ISSUE THREAD

**Issue by mparkhill** [symbiote/silverstripe-advancedworkflow#56]
The NotifyUsersWorkflow action currently sends emails as html, so if you enter plain text in the email template all the line returns are gone. If you enter html text then the textarea is quite small and not ideal for editing such content. The issue is that the action does not detect a plaintext email body and send using Email::sendPlain.

A solution could be for the action to have the ability for the user to specify either plain text or html format, this would then change the edit action form field from a TextareaField to an HtmlEditorField. 

Also it would be nice that if there was a .ss template present for the notify emails for there to be some indication of this in the edit action form, to inform the user that they don't need to edit the email body in the action.

**Comment by robbieaverill** [comment]
Feel free to reopen this issue if it's still relevant/wanted five years on!
