### ISSUE TITLE
Show diff of changes as part of workflow

### ISSUE THREAD

**Issue by sminnee** [symbiote/silverstripe-advancedworkflow#94]
When submitting a change for approval, the person approving needs to easily see what has changed.  The cmsworkflow module had this feature, showing a field-by-field diff with red/green highlighting.

This content should be shown in two places:
- Workflow emails
- The workflow screen

No designs currently exist, AFAIK

**Comment by robbieaverill** [comment]
We can close this as a duplicate of #173 (even though it's older). Diff views exist already in the web interface, but need to be added to emails still.
